name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
      description: What you expected to happen and what actually happened.
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: If applicable, add screenshots or recordings.
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (crash/data loss)
        - Major (feature broken)
        - Minor (cosmetic/workaround exists)
        - Trivial
    validations:
      required: true

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: e.g. 15.2
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Found in Settings > About
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before Submitting
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: This report describes a single bug.
          required: true
        - label: I am using the latest version.
          required: true
