name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve or what opportunity does it create?
      placeholder: |
        I'm always frustrated when...
        It would be useful to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How you'd like this to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought of.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, references, or any other context.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before Submitting
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: This request describes a single feature.
          required: true
